#!/usr/bin/env bash
set -Eeuo pipefail

peer_address=${1:?Missing peer overlay address}
peer_name=${2:?Missing peer DNS name}
server_ip=${3:?Missing coordination server address}
mesh_mark=${4:?Missing mesh socket mark}
mesh_table=${5:?Missing mesh route table}
mesh_priority=${6:?Missing mesh rule priority}
operator_ip=${SSH_CLIENT%% *}

route_to_operator=$(ip -4 route get "$operator_ip" | head -n 1)
gateway=$(awk \
  '{ for (i = 1; i <= NF; i++) if ($i == "via") { print $(i + 1); exit } }' \
  <<<"$route_to_operator")
interface=$(awk \
  '{ for (i = 1; i <= NF; i++) if ($i == "dev") { print $(i + 1); exit } }' \
  <<<"$route_to_operator")
[[ -n $interface ]] || { printf 'Could not determine the SSH underlay interface.\n' >&2; exit 1; }

operator_route=$(ip -4 route show "$operator_ip/32" | head -n 1 || true)
server_route=$(ip -4 route show "$server_ip/32" | head -n 1 || true)

restore_host_route() {
  local address=$1
  local original=$2
  ip -4 route del "$address/32" 2>/dev/null || true
  if [[ -n $original ]]; then
    # Route text is generated by iproute2 and intentionally split back into arguments.
    # shellcheck disable=SC2086
    ip -4 route replace $original 2>/dev/null || true
  fi
}

cleanup() {
  ip -4 rule del priority "$mesh_priority" \
    not fwmark "$mesh_mark" lookup "$mesh_table" 2>/dev/null || true
  ip -4 rule del priority "$((mesh_priority + 1))" \
    table main suppress_prefixlength 0 2>/dev/null || true
  ip -4 route flush table "$mesh_table" 2>/dev/null || true
  restore_host_route "$server_ip" "$server_route"
  restore_host_route "$operator_ip" "$operator_route"
}
trap cleanup EXIT

for address in "$operator_ip" "$server_ip"; do
  if [[ -n $gateway ]]; then
    ip -4 route replace "$address/32" via "$gateway" dev "$interface"
  else
    ip -4 route replace "$address/32" dev "$interface"
  fi
done

ip -4 route replace table "$mesh_table" default dev svpn0
ip -4 rule add priority "$mesh_priority" \
  not fwmark "$mesh_mark" lookup "$mesh_table"
ip -4 rule add priority "$((mesh_priority + 1))" \
  table main suppress_prefixlength 0

[[ $(ip -4 route get 1.1.1.1 | awk '/dev/ { for (i=1;i<=NF;i++) if ($i=="dev") { print $(i+1); exit } }') == svpn0 ]]
[[ $(ip -4 route get "$server_ip" mark "$mesh_mark" | awk '/dev/ { for (i=1;i<=NF;i++) if ($i=="dev") { print $(i+1); exit } }') == "$interface" ]]
ping -4 -c 2 -W 4 "$peer_address" >/dev/null
response=$(curl -4 --noproxy '*' --fail --silent --show-error \
  --connect-timeout 5 --max-time 15 "http://$peer_name/")
[[ $response == vpn-mesh-nginx-ok ]]

printf 'Full-tunnel mesh check passed: default via svpn0; marked UDP via %s; %s reachable.\n' \
  "$interface" "$peer_name"
