#!/usr/bin/env bash

# Shared diagnostics, dependency checks, state loading, and validation.

log() {
  printf '[%s] %s\n' "${VPNSAMPLE_LOG_PREFIX:-vpnsample}" "$*"
}

fail() {
  printf '[%s] ERROR: %s\n' "${VPNSAMPLE_LOG_PREFIX:-vpnsample}" "$*" >&2
  exit 1
}

need() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"
}

need_all() {
  local command
  for command in "$@"; do
    need "$command"
  done
}

load_state() {
  local state_file=$1
  [[ -f $state_file ]] || fail "State file not found: $state_file"
  # State files are generated by VPNSample with shell-escaped values only.
  # shellcheck disable=SC1090
  source "$state_file"
}

state_value() {
  bash -c 'source "$1"; printf "%s" "${!2}"' _ "$1" "$2"
}

validate_port() {
  local value=$1
  [[ $value =~ ^[0-9]+$ ]] && ((value >= 1 && value <= 65535)) \
    || fail "VPN_PORT must be an integer from 1 to 65535."
}

validate_boolean() {
  local name=$1
  local value=$2
  [[ $value == 0 || $value == 1 ]] || fail "$name must be 0 or 1."
}
