#!/usr/bin/env bash
set -Eeuo pipefail

: "${RUVDS_IP:?RUVDS_IP is required}"
: "${RUVDS_USER:?RUVDS_USER is required}"
: "${RUVDS_PASSWORD:?RUVDS_PASSWORD is required}"

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
project_root=${VPNSAMPLE_ROOT:-$(cd -- "$script_dir/.." && pwd)}
state_file=${VPN_STATE_FILE:-$project_root/.vpn-droplet.env}
[[ -f $state_file ]] || { echo "State file not found: $state_file" >&2; exit 1; }
# Generated by VPNSample with shell-escaped values.
source "$state_file"
: "${DROPLET_IP:?DROPLET_IP is missing from $state_file}"
VPN_PORT=${VPN_PORT:-443}
VPN_TLS_SERVER_NAME=${VPN_TLS_SERVER_NAME:-vpn.twocubes.io}
VPN_COVER_TOKEN=${VPN_COVER_TOKEN:-}
: "${VPN_TLS_PINNED_CERTIFICATE:?VPN_TLS_PINNED_CERTIFICATE is missing from $state_file}"
[[ -f $VPN_TLS_PINNED_CERTIFICATE ]] || { echo "Certificate not found: $VPN_TLS_PINNED_CERTIFICATE" >&2; exit 1; }

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
known_hosts=$script_dir/.ruvds_known_hosts
work_dir=$(mktemp -d /tmp/vpnsample-ruvds-deploy.XXXXXXXX)
askpass=$work_dir/askpass
cleanup() { rm -rf -- "$work_dir"; }
trap cleanup EXIT
printf '#!/usr/bin/env bash\nprintf '\''%%s\\n'\'' "$RUVDS_PASSWORD"\n' >"$askpass"
chmod 700 "$askpass"
export SSH_ASKPASS=$askpass SSH_ASKPASS_REQUIRE=force
ssh_opts=(-o StrictHostKeyChecking=accept-new -o "UserKnownHostsFile=$known_hosts" -o PreferredAuthentications=password -o PubkeyAuthentication=no)

dotnet restore "$project_root/Client/Client.csproj" --disable-parallel
dotnet build "$project_root/Client/Client.csproj" -c Release --disable-build-servers --no-restore -m:1

setsid -w ssh "${ssh_opts[@]}" "$RUVDS_USER@$RUVDS_IP" bash -s -- /opt/vpnsample-client false true \
  <"$project_root/scripts/remote/configure-client.sh"

cat >"$work_dir/client-launcher.sh" <<'LAUNCHER'
#!/usr/bin/env bash
set -Eeuo pipefail
server_ip=$1
server_port=$2
server_name=$3
certificate=$4
cover_token=${5:-}
default_route=$(ip -4 route show default | head -n1)
gateway=$(awk '{ for (i=1; i<=NF; i++) if ($i == "via") print $(i+1) }' <<<"$default_route")
interface=$(awk '{ for (i=1; i<=NF; i++) if ($i == "dev") print $(i+1) }' <<<"$default_route")
public_ip=$(ip -o -4 address show dev "$interface" scope global | awk '{ split($4,a,"/"); print a[1]; exit }')
test -n "$gateway"; test -n "$interface"; test -n "$public_ip"
cleanup() {
  status=$?
  trap - EXIT INT TERM
  if [[ -n ${client_pid:-} ]]; then kill "$client_pid" 2>/dev/null || true; wait "$client_pid" 2>/dev/null || true; fi
  iptables -t nat -D POSTROUTING -o svpn0 ! -s 10.8.0.0/24 -j SNAT --to-source "${tunnel_ip:-10.8.0.2}" 2>/dev/null || true
  ip6tables -t nat -D POSTROUTING -o svpn0 ! -s fd42:8::/64 -j SNAT --to-source "${tunnel_ipv6:-fd42:8::2}" 2>/dev/null || true
  iptables -D OUTPUT -o svpn0 ! -s 10.8.0.0/24 -j DROP 2>/dev/null || true
  ip6tables -D OUTPUT -o svpn0 ! -s fd42:8::/64 -j DROP 2>/dev/null || true
  ip -4 rule del priority 100 from "$public_ip/32" ipproto tcp sport 22 table 100 2>/dev/null || true
  ip -4 route flush table 100 2>/dev/null || true
  ip -4 route replace default via "$gateway" dev "$interface" || true
  exit "$status"
}
trap cleanup EXIT INT TERM
env VPN_TLS_SERVER_NAME="$server_name" VPN_TLS_PINNED_CERTIFICATE="$certificate" VPN_COVER_TOKEN="$cover_token" \
  /opt/vpnsample-client/dotnet/dotnet /opt/vpnsample-client/app/Client.dll "$server_ip" "$server_port" &
client_pid=$!
for attempt in $(seq 1 30); do
  ip link show svpn0 >/dev/null 2>&1 && break
  kill -0 "$client_pid"
  ((attempt < 30)); sleep 1
done
tunnel_ip=$(ip -o -4 address show dev svpn0 | awk '{ split($4,a,"/"); print a[1]; exit }')
tunnel_ipv6=$(ip -o -6 address show dev svpn0 scope global | awk '{ split($4,a,"/"); print a[1]; exit }')
test -n "$tunnel_ip"; test -n "$tunnel_ipv6"
iptables -t nat -C POSTROUTING -o svpn0 ! -s 10.8.0.0/24 -j SNAT --to-source "$tunnel_ip" 2>/dev/null || iptables -t nat -A POSTROUTING -o svpn0 ! -s 10.8.0.0/24 -j SNAT --to-source "$tunnel_ip"
ip6tables -t nat -C POSTROUTING -o svpn0 ! -s fd42:8::/64 -j SNAT --to-source "$tunnel_ipv6" 2>/dev/null || ip6tables -t nat -A POSTROUTING -o svpn0 ! -s fd42:8::/64 -j SNAT --to-source "$tunnel_ipv6"
iptables -C OUTPUT -o svpn0 ! -s 10.8.0.0/24 -j DROP 2>/dev/null || iptables -A OUTPUT -o svpn0 ! -s 10.8.0.0/24 -j DROP
ip6tables -C OUTPUT -o svpn0 ! -s fd42:8::/64 -j DROP 2>/dev/null || ip6tables -A OUTPUT -o svpn0 ! -s fd42:8::/64 -j DROP
ip -4 route replace "$server_ip/32" via "$gateway" dev "$interface"
ip -4 route replace table 100 default via "$gateway" dev "$interface"
ip -4 rule del priority 100 from "$public_ip/32" table 100 2>/dev/null || true
ip -4 rule del priority 100 from "$public_ip/32" ipproto tcp sport 22 table 100 2>/dev/null || true
ip -4 rule add priority 100 from "$public_ip/32" ipproto tcp sport 22 table 100
ip -4 route replace default dev svpn0 src "$tunnel_ip"
ip -6 route replace default dev svpn0 metric 50
wait "$client_pid"
LAUNCHER

cat >"$work_dir/vpnsample-client.service" <<SERVICE
[Unit]
Description=VPNSample RUVDS VPN client
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
ExecStart=/opt/vpnsample-client/client-launcher.sh $DROPLET_IP $VPN_PORT $VPN_TLS_SERVER_NAME /opt/vpnsample-client/tls.crt $VPN_COVER_TOKEN
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
SERVICE

client_bin=$project_root/Client/bin/Release/net10.0
shopt -s nullglob
client_files=("$client_bin"/*.dll "$client_bin"/*.json)
shopt -u nullglob
((${#client_files[@]})) || { echo "No client build artifacts found in $client_bin" >&2; exit 1; }
setsid -w ssh "${ssh_opts[@]}" "$RUVDS_USER@$RUVDS_IP" 'systemctl stop vpnsample-client.service 2>/dev/null || true; rm -rf /opt/vpnsample-client/app && mkdir -p /opt/vpnsample-client/app'
setsid -w scp "${ssh_opts[@]}" "${client_files[@]}" "$RUVDS_USER@$RUVDS_IP:/opt/vpnsample-client/app/"
setsid -w scp "${ssh_opts[@]}" "$VPN_TLS_PINNED_CERTIFICATE" "$work_dir/client-launcher.sh" "$work_dir/vpnsample-client.service" "$RUVDS_USER@$RUVDS_IP:/opt/vpnsample-client/"
setsid -w ssh "${ssh_opts[@]}" "$RUVDS_USER@$RUVDS_IP" bash -s <<'REMOTE'
set -Eeuo pipefail
apt-get -o DPkg::Lock::Timeout=300 install -y -qq iptables >/dev/null
cert=$(find /opt/vpnsample-client -maxdepth 1 -type f -name '*.crt' ! -name tls.crt | head -n1)
if [[ -n $cert ]]; then mv "$cert" /opt/vpnsample-client/tls.crt; fi
mv /opt/vpnsample-client/vpnsample-client.service /etc/systemd/system/vpnsample-client.service
chmod 700 /opt/vpnsample-client/client-launcher.sh
chmod 644 /opt/vpnsample-client/tls.crt /etc/systemd/system/vpnsample-client.service
systemctl daemon-reload
systemctl enable vpnsample-client.service
systemctl restart vpnsample-client.service
systemctl is-active --quiet vpnsample-client.service
REMOTE

echo "RUVDS VPN client deployed. Run: $script_dir/e2e-ruvds.sh"
