#!/usr/bin/env bash
set -Eeuo pipefail

: "${RUVDS_IP:?RUVDS_IP is required}"
: "${RUVDS_USER:?RUVDS_USER is required}"
: "${RUVDS_PASSWORD:?RUVDS_PASSWORD is required}"

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
project_root=${VPNSAMPLE_ROOT:-$(cd -- "$script_dir/.." && pwd)}
state_file=${VPN_STATE_FILE:-$project_root/.vpn-droplet.env}
[[ -f $state_file ]] || { echo "State file not found: $state_file" >&2; exit 1; }
# Generated by VPNSample with shell-escaped values.
source "$state_file"
: "${DROPLET_IP:?DROPLET_IP is missing from $state_file}"
: "${DROPLET_IPV6:?DROPLET_IPV6 is missing from $state_file}"

known_hosts=$script_dir/.ruvds_known_hosts
askpass=$(mktemp /tmp/ruvds-askpass.XXXXXXXX)
cleanup() { rm -f -- "$askpass"; }
trap cleanup EXIT
printf '#!/usr/bin/env bash\nprintf '\''%%s\\n'\'' "$RUVDS_PASSWORD"\n' >"$askpass"
chmod 700 "$askpass"
export SSH_ASKPASS=$askpass SSH_ASKPASS_REQUIRE=force

setsid -w ssh \
  -o StrictHostKeyChecking=accept-new \
  -o "UserKnownHostsFile=$known_hosts" \
  -o PreferredAuthentications=password \
  -o PubkeyAuthentication=no \
  "$RUVDS_USER@$RUVDS_IP" bash -s -- "$DROPLET_IP" "$DROPLET_IPV6" <<'REMOTE'
set -Eeuo pipefail
expected_v4=$1
expected_v6=$2

test "$(systemctl is-active vpnsample-client.service)" = active
test -e /sys/class/net/svpn0
ping -c 2 -W 4 10.8.0.1 >/dev/null
ping -6 -c 2 -W 4 fd42:8::1 >/dev/null
route4=$(ip -4 route get 1.1.1.1)
route6=$(ip -6 route get 2606:4700:4700::1111)
[[ " $route4 " == *" dev svpn0 "* ]]
[[ " $route6 " == *" dev svpn0 "* ]]
exit4=$(curl -4fsS --connect-timeout 15 https://api.ipify.org)
exit6=$(curl -6fsS --connect-timeout 15 https://api64.ipify.org)
test "$exit4" = "$expected_v4"
test "$exit6" = "$expected_v6"
instagram_code=$(curl -4LsS -o /dev/null -w '%{http_code}' --connect-timeout 15 --max-time 45 https://www.instagram.com/)
[[ $instagram_code =~ ^(200|301|302|303|307|308)$ ]]
printf 'VPN E2E passed\nIPv4 exit: %s\nIPv6 exit: %s\nInstagram HTTP: %s\n' "$exit4" "$exit6" "$instagram_code"
REMOTE
