#!/usr/bin/env bash
set -Eeuo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
project_root=${VPNSAMPLE_ROOT:-$(cd -- "$script_dir/.." && pwd)}
state_file=${VPN_STATE_FILE:-$project_root/.vpn-droplet.env}
output_dir=${STANDARD_VPN_OUTPUT_DIR:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/standard-vpn-clients}
[[ -f $state_file ]] || { echo "State file not found: $state_file" >&2; exit 1; }
# Generated by VPNSample with shell-escaped values.
source "$state_file"
: "${DROPLET_IP:?DROPLET_IP is missing from $state_file}"
: "${SSH_KEY_PATH:?SSH_KEY_PATH is missing from $state_file}"
[[ -f $SSH_KEY_PATH ]] || { echo "SSH key not found: $SSH_KEY_PATH" >&2; exit 1; }
chmod 600 "$SSH_KEY_PATH"

work_dir=$(mktemp -d /tmp/standard-vpn-setup.XXXXXXXX)
cleanup() { rm -rf -- "$work_dir"; }
trap cleanup EXIT
known_hosts=$work_dir/known_hosts
ssh_opts=(-i "$SSH_KEY_PATH" -o IdentityAgent=none -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new -o "UserKnownHostsFile=$known_hosts")

ssh "${ssh_opts[@]}" "root@$DROPLET_IP" bash -s -- "$DROPLET_IP" <<'REMOTE'
set -Eeuo pipefail
server_ip=$1
export DEBIAN_FRONTEND=noninteractive
apt-get -o DPkg::Lock::Timeout=300 update -qq
apt-get -o DPkg::Lock::Timeout=300 install -y -qq openvpn wireguard-tools iptables openssl >/dev/null
install -d -m 700 /etc/openvpn/standard-pki /root/standard-vpn-clients
pki=/etc/openvpn/standard-pki

if [[ ! -s $pki/ca.key ]]; then
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:3072 -out "$pki/ca.key"
  openssl req -x509 -new -sha256 -days 3650 -key "$pki/ca.key" -subj /CN=VPNSample-Standard-CA -out "$pki/ca.crt"
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:3072 -out "$pki/server.key"
  openssl req -new -key "$pki/server.key" -subj /CN=vpnsample-openvpn -out "$pki/server.csr"
  printf 'basicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\nsubjectAltName=IP:%s\n' "$server_ip" >"$pki/server.ext"
  openssl x509 -req -days 825 -sha256 -in "$pki/server.csr" -CA "$pki/ca.crt" -CAkey "$pki/ca.key" -CAcreateserial -extfile "$pki/server.ext" -out "$pki/server.crt"
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:3072 -out "$pki/client.key"
  openssl req -new -key "$pki/client.key" -subj /CN=vpnsample-e2e-client -out "$pki/client.csr"
  printf 'basicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=clientAuth\n' >"$pki/client.ext"
  openssl x509 -req -days 825 -sha256 -in "$pki/client.csr" -CA "$pki/ca.crt" -CAkey "$pki/ca.key" -CAcreateserial -extfile "$pki/client.ext" -out "$pki/client.crt"
  openvpn --genkey secret "$pki/tls-crypt.key"
fi

if ! openssl x509 -in "$pki/server.crt" -noout -text | grep -q 'Digital Signature'; then
  printf 'basicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\nsubjectAltName=IP:%s\n' "$server_ip" >"$pki/server.ext"
  openssl x509 -req -days 825 -sha256 -in "$pki/server.csr" -CA "$pki/ca.crt" -CAkey "$pki/ca.key" -CAcreateserial -extfile "$pki/server.ext" -out "$pki/server.crt"
  printf 'basicConstraints=CA:FALSE\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=clientAuth\n' >"$pki/client.ext"
  openssl x509 -req -days 825 -sha256 -in "$pki/client.csr" -CA "$pki/ca.crt" -CAkey "$pki/ca.key" -CAcreateserial -extfile "$pki/client.ext" -out "$pki/client.crt"
fi

cat >/etc/openvpn/server/standard.conf <<EOF
port 1194
proto udp4
dev ovpn-standard
dev-type tun
topology subnet
server 10.90.0.0 255.255.255.0
ca $pki/ca.crt
cert $pki/server.crt
key $pki/server.key
dh none
ecdh-curve prime256v1
tls-crypt $pki/tls-crypt.key
auth SHA256
cipher AES-256-GCM
data-ciphers AES-256-GCM
keepalive 10 60
persist-key
persist-tun
user nobody
group nogroup
verb 3
EOF

cat >/root/standard-vpn-clients/openvpn-client.ovpn <<EOF
client
dev tun
proto udp4
remote $server_ip 1194
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA256
cipher AES-256-GCM
data-ciphers AES-256-GCM
verb 3
<ca>
$(cat "$pki/ca.crt")
</ca>
<cert>
$(cat "$pki/client.crt")
</cert>
<key>
$(cat "$pki/client.key")
</key>
<tls-crypt>
$(cat "$pki/tls-crypt.key")
</tls-crypt>
EOF

install -d -m 700 /etc/wireguard
if [[ ! -s /etc/wireguard/server.key ]]; then
  umask 077
  wg genkey >/etc/wireguard/server.key
  wg pubkey </etc/wireguard/server.key >/etc/wireguard/server.pub
  wg genkey >/etc/wireguard/client.key
  wg pubkey </etc/wireguard/client.key >/etc/wireguard/client.pub
fi
server_private=$(cat /etc/wireguard/server.key)
server_public=$(cat /etc/wireguard/server.pub)
client_private=$(cat /etc/wireguard/client.key)
client_public=$(cat /etc/wireguard/client.pub)
out_interface=$(ip -4 route show default | awk 'NR==1 { for(i=1;i<=NF;i++) if($i=="dev") {print $(i+1); exit} }')
cat >/etc/wireguard/wg-standard.conf <<EOF
[Interface]
Address = 10.91.0.1/24
ListenPort = 51820
PrivateKey = $server_private
PostUp = iptables -t nat -C POSTROUTING -s 10.91.0.0/24 -o $out_interface -j MASQUERADE || iptables -t nat -A POSTROUTING -s 10.91.0.0/24 -o $out_interface -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s 10.91.0.0/24 -o $out_interface -j MASQUERADE || true

[Peer]
PublicKey = $client_public
AllowedIPs = 10.91.0.2/32
EOF
cat >/root/standard-vpn-clients/wireguard-client.conf <<EOF
[Interface]
Address = 10.91.0.2/24
PrivateKey = $client_private

[Peer]
PublicKey = $server_public
Endpoint = $server_ip:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 15
EOF
chmod 600 /etc/wireguard/wg-standard.conf /root/standard-vpn-clients/*

cat >/etc/systemd/system/standard-vpn-nat.service <<EOF
[Unit]
Description=NAT for standard VPN tests
After=network-online.target
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/sh -c '/usr/sbin/sysctl -w net.ipv4.ip_forward=1; /usr/sbin/iptables -t nat -C POSTROUTING -s 10.90.0.0/24 -o $out_interface -j MASQUERADE || /usr/sbin/iptables -t nat -A POSTROUTING -s 10.90.0.0/24 -o $out_interface -j MASQUERADE'
ExecStop=/bin/sh -c '/usr/sbin/iptables -t nat -D POSTROUTING -s 10.90.0.0/24 -o $out_interface -j MASQUERADE || true'
[Install]
WantedBy=multi-user.target
EOF
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q '^Status: active'; then
  ufw allow 1194/udp >/dev/null
  ufw allow 51820/udp >/dev/null
fi
systemctl daemon-reload
systemctl enable standard-vpn-nat.service openvpn-server@standard.service wg-quick@wg-standard.service
systemctl restart standard-vpn-nat.service openvpn-server@standard.service wg-quick@wg-standard.service
systemctl is-active --quiet openvpn-server@standard.service
systemctl is-active --quiet wg-quick@wg-standard.service
ss -lun | grep -q ':1194 '
ss -lun | grep -q ':51820 '
REMOTE

mkdir -p "$output_dir"
scp "${ssh_opts[@]}" "root@$DROPLET_IP:/root/standard-vpn-clients/openvpn-client.ovpn" "$output_dir/openvpn-client.ovpn"
scp "${ssh_opts[@]}" "root@$DROPLET_IP:/root/standard-vpn-clients/wireguard-client.conf" "$output_dir/wireguard-client.conf"
chmod 600 "$output_dir/openvpn-client.ovpn" "$output_dir/wireguard-client.conf"
printf 'Standard VPN servers are active on %s\nOpenVPN: UDP/1194\nWireGuard: UDP/51820\nClient profiles: %s\n' "$DROPLET_IP" "$output_dir"
